-- Xóa bảng có khóa ngoại trước khi xóa các bảng chính
DROP TABLE IF EXISTS ChiTietHoaDon;
DROP TABLE IF EXISTS PhaChe;
DROP TABLE IF EXISTS SanPham;
DROP TABLE IF EXISTS LoaiSanPham;
DROP TABLE IF EXISTS DonHang;
DROP TABLE IF EXISTS KhachHang;
DROP TABLE IF EXISTS ThucHien;
DROP TABLE IF EXISTS CaLamViec;
DROP TABLE IF EXISTS NhanVienBanThoiGian;
DROP TABLE IF EXISTS NhanVienToanThoiGian;
DROP TABLE IF EXISTS NhanVien;
DROP TABLE IF EXISTS CongViec;
DROP TABLE IF EXISTS NguyenLieu;


ALTER TABLE ThucHien
ADD CONSTRAINT PK_ThucHien PRIMARY KEY (MaKH, MaCV, MaNV);
